/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admins/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registriert Admin+Mandant
         * @description Erstellt einen neuen Mandanten inklusive Admin-Zugang.
         */
        post: operations["registerAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/registration-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Einmaliger Registrierungslink (TTL 15m)
         * @description Generiert einen einmaligen Link, mit dem ein Mitarbeitergerät binnen 15 Minuten registriert wird.
         */
        post: operations["createDeviceRegistrationLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/register/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bestätigt Gerätebindung (einmalig)
         * @description Schliesst den Device-Proof-Flow ab und verknüpft das Gerät dauerhaft mit dem Tenant.
         */
        post: operations["confirmDeviceRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stamps/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Erzeugt einmaligen Stempel-Token (QR)
         * @description Erstellt einen kurzlebigen QR-Token zum Ausstellen eines digitalen Stempels.
         */
        post: operations["createStampToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stamps/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Löst Stempel ein; qualifiziert ggf. Referral und bucht Bonus
         * @description Validiert QR-Token, bucht Stempel, bewertet Referral-Status und Plan-Gates.
         */
        post: operations["claimStamp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rewards/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Löst eine Prämie ein
         * @description Validiert Redeem-Token via Device-Proof und markiert Prämie als verbraucht.
         */
        post: operations["redeemReward"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liefert personalisierten Referral-Link (Werber)
         * @description Gibt den aktiven Refer-a-Friend-Link für eine pseudonyme Card-ID zurück.
         */
        get: operations["getReferralLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @enum {string} */
            error_code?: "TOKEN_EXPIRED" | "TOKEN_REUSE" | "SELF_REFERRAL_BLOCKED" | "REFERRAL_LIMIT_REACHED" | "REFERRAL_TENANT_MISMATCH" | "PLAN_NOT_ALLOWED" | "RATE_LIMITED";
            correlation_id?: string;
            retry_after?: number;
        } & {
            [key: string]: unknown;
        };
        StampTokenResponse: {
            qrToken: string;
            jti: string;
            /** Format: date-time */
            expiresAt: string;
        };
        StampClaimRequest: {
            qrToken: string;
            ref?: string | null;
        };
        StampClaimResponse: {
            /** @enum {string} */
            status: "claimed";
            /** Format: uuid */
            stampId: string;
            rewardUnlocked?: boolean;
            referralAwarded?: boolean;
            remainingToReward?: number;
            correlation_id?: string;
        };
        RewardRedeemResponse: {
            /** @enum {string} */
            status: "redeemed";
            /** Format: uuid */
            rewardId: string;
            tenant_id?: string;
            device_id?: string;
            correlation_id?: string;
        };
    };
    responses: {
        /** @description Bad Request */
        BadRequestProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unauthorized */
        UnauthorizedProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Forbidden */
        ForbiddenProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Conflict */
        ConflictProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unprocessable Entity */
        UnprocessableEntityProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Too Many Requests */
        TooManyRequestsProblem: {
            headers: {
                "Retry-After": components["headers"]["Retry-After"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Internal Server Error */
        InternalServerErrorProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Idempotency protection (TTL 24h); must not contain PII. */
        IdempotencyKey: string;
        /** @description Ed25519 proof over method|path|timestamp|jti; max drift ±30s. */
        XDeviceProof: string;
        /** @description Unix epoch seconds used in Device-Proof; drift ±30s allowed. */
        XDeviceTimestamp: number;
    };
    requestBodies: never;
    headers: {
        /** @description Echoes the request Idempotency-Key when provided. */
        "Idempotency-Key": string;
        /** @description Number of seconds to wait before retrying. */
        "Retry-After": number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["ConflictProblem"];
        };
    };
    createDeviceRegistrationLink: {
        parameters: {
            query?: never;
            header: {
                /** @description Idempotency protection (TTL 24h); must not contain PII. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["ConflictProblem"];
            429: components["responses"]["TooManyRequestsProblem"];
        };
    };
    confirmDeviceRegistration: {
        parameters: {
            query?: never;
            header: {
                /** @description Idempotency protection (TTL 24h); must not contain PII. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequestProblem"];
            409: components["responses"]["ConflictProblem"];
        };
    };
    createStampToken: {
        parameters: {
            query?: never;
            header: {
                /** @description Idempotency protection (TTL 24h); must not contain PII. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StampTokenResponse"];
                };
            };
            /** @description RATE_LIMITED */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    claimStamp: {
        parameters: {
            query?: never;
            header: {
                /** @description Idempotency protection (TTL 24h); must not contain PII. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StampClaimRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Idempotency-Key": components["headers"]["Idempotency-Key"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StampClaimResponse"];
                };
            };
            400: components["responses"]["BadRequestProblem"];
            403: components["responses"]["ForbiddenProblem"];
            409: components["responses"]["ConflictProblem"];
            422: components["responses"]["UnprocessableEntityProblem"];
            429: components["responses"]["TooManyRequestsProblem"];
        };
    };
    redeemReward: {
        parameters: {
            query?: never;
            header: {
                /** @description Ed25519 proof over method|path|timestamp|jti; max drift ±30s. */
                "X-Device-Proof": components["parameters"]["XDeviceProof"];
                /** @description Unix epoch seconds used in Device-Proof; drift ±30s allowed. */
                "X-Device-Timestamp": components["parameters"]["XDeviceTimestamp"];
                /** @description Idempotency protection (TTL 24h); must not contain PII. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    redeemToken: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Idempotency-Key": components["headers"]["Idempotency-Key"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RewardRedeemResponse"];
                };
            };
            400: components["responses"]["BadRequestProblem"];
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["ForbiddenProblem"];
            409: components["responses"]["ConflictProblem"];
            429: components["responses"]["TooManyRequestsProblem"];
            500: components["responses"]["InternalServerErrorProblem"];
        };
    };
    getReferralLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        refCodeURL: string;
                    };
                };
            };
            401: components["responses"]["UnauthorizedProblem"];
        };
    };
}
