/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admins/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registriert Admin+Mandant
         * @description Creates the initial admin account and tenant.
         */
        post: operations["registerAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admins/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin login
         * @description Issues a new admin session for valid credentials.
         */
        post: operations["loginAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admins/reporting/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liefert aggregierte KPIs fuer das Admin-Dashboard
         * @description Aggregated stamps/rewards/referral KPIs and plan usage.
         */
        get: operations["getReportingSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admins/reporting/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liefert Zeitreihen fuer Reporting-Metriken
         * @description Time series buckets for stamps, rewards, and referral metrics.
         */
        get: operations["getReportingTimeseries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admins/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liefert aktuellen Plan inkl. Limits und Feature-Flags
         * @description Admin endpoint for plan overview and upgrade hints.
         */
        get: operations["getAdminPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admins/offers/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liefert aktuelles Angebot
         * @description Admin endpoint to read the current offer snippet.
         */
        get: operations["getCurrentOffer"];
        /**
         * Setzt oder aktualisiert aktuelles Angebot (idempotent)
         * @description Admin endpoint to upsert the current offer snippet.
         */
        put: operations["upsertCurrentOffer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admins/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh admin session
         * @description Refreshes an admin session using a refresh token.
         */
        post: operations["refreshAdminSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admins/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout admin session
         * @description Revokes the current admin session.
         */
        post: operations["logoutAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admins/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listet Audit-Events
         * @description Read-only audit feed for admin. Filterable by device_id and optional event_type.
         */
        get: operations["listAdminAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * JWKS
         * @description Returns the public JWKS for token verification.
         */
        get: operations["getJwks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listet Mitarbeiter-Geraete
         * @description Returns devices for the current tenant.
         */
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sperrt ein Geraet
         * @description Idempotent.
         */
        post: operations["blockDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/unblock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reaktiviert ein Geraet
         * @description Idempotent.
         */
        post: operations["unblockDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Entfernt ein Geraet
         * @description Idempotent.
         */
        delete: operations["removeDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/registration-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Erzeugt einmaligen Registrierungslink (TTL 15 Min)
         * @description Idempotent. Link ist einmalig und zeitlich begrenzt.
         */
        post: operations["createDeviceRegistrationLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/register/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bestätigt Gerätebindung
         * @description Einmalig verwendbar. Idempotent. Sicherheits-E-Mail wird versendet.
         */
        post: operations["confirmDeviceRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dsr/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create DSR request
         * @description Creates a DSR request and records a tombstone on fulfillment.
         */
        post: operations["createDsrRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dsr/requests/{dsr_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get DSR request status
         * @description Returns status and metadata for a DSR request.
         */
        get: operations["getDsrRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dsr/requests/{dsr_id}/fulfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fulfill DSR request
         * @description Triggers deletion/pseudonymization and inserts tombstone records.
         */
        post: operations["fulfillDsrRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stamps/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Erzeugt einmaligen Stempel-Token (QR)
         * @description Issues a one-time stamp token for client scan.
         */
        post: operations["createStampToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stamps/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Löst Stempel ein; qualifiziert ggf. Referral und bucht Bonus
         * @description Claims a stamp and applies referral rules if eligible.
         */
        post: operations["claimStamp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rewards/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Löst eine Prämie ein
         * @description Redeems a reward for a valid redemption token.
         */
        post: operations["redeemReward"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liefert personalisierten Referral-Link (Werber)
         * @description Returns the referral link for an existing customer.
         */
        get: operations["getReferralLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC7807 Problem Details. In Lokaltreu responses, error_code is always present for application-level errors; correlation_id is optional and provided for support/debugging. */
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @enum {string} */
            error_code?: "TOKEN_EXPIRED" | "TOKEN_REUSE" | "SELF_REFERRAL_BLOCKED" | "REFERRAL_LIMIT_REACHED" | "REFERRAL_TENANT_MISMATCH" | "REFERRAL_CODE_INVALID" | "PLAN_NOT_ALLOWED" | "RATE_LIMITED" | "IDEMPOTENCY_KEY_REQUIRED" | "IDEMPOTENCY_KEY_INVALID" | "DEVICE_NOT_FOUND" | "DEVICE_STATUS_CONFLICT";
            correlation_id?: string;
            retry_after?: number;
        } & {
            [key: string]: unknown;
        };
        AdminLoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AdminRefreshRequest: {
            refreshToken: string;
        };
        AdminSessionResponse: {
            accessToken: string;
            refreshToken: string;
            expiresIn: number;
        };
        AdminRegistrationResponse: {
            /** Format: uuid */
            adminId: string;
            /** Format: uuid */
            tenantId: string;
            accessToken: string;
            refreshToken: string;
            expiresIn: number;
        };
        JwksResponse: {
            keys: Record<string, never>[];
        };
        DsrSubject: {
            /** @enum {string} */
            subject_type: "card_id" | "device_id" | "subject_id";
            subject_id: string;
        };
        DsrRequestCreateRequest: {
            /** @enum {string} */
            requestType: "DELETE" | "ERASURE";
            subject: components["schemas"]["DsrSubject"];
            reason?: string;
        };
        DsrRequestResponse: {
            /** Format: uuid */
            dsrRequestId: string;
            /** @enum {string} */
            status: "PENDING" | "FULFILLED" | "REJECTED";
            /** @enum {string} */
            requestType: "DELETE" | "ERASURE";
            subject: components["schemas"]["DsrSubject"];
            /** Format: date-time */
            createdAt: string;
        };
        DsrRequestStatusResponse: {
            /** Format: uuid */
            dsrRequestId: string;
            /** @enum {string} */
            status: "PENDING" | "FULFILLED" | "REJECTED";
            /** @enum {string} */
            requestType: "DELETE" | "ERASURE";
            subject: components["schemas"]["DsrSubject"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            fulfilledAt?: string | null;
        };
        DsrFulfillRequest: {
            /** @enum {string} */
            action?: "DELETE" | "PSEUDONYMIZE";
        };
        StampTokenResponse: {
            qrToken: string;
            jti: string;
            /** Format: date-time */
            expiresAt: string;
        };
        StampClaimRequest: {
            qrToken: string;
            ref?: string | null;
        };
        CardState: {
            currentStamps: number;
            stampsRequired: number;
            rewardsAvailable: number;
        };
        OfferSnippet: {
            title: string;
            body?: string | null;
        };
        AdminOffer: {
            title: string;
            body?: string | null;
            active?: boolean | null;
            /** Format: date-time */
            activeFrom?: string | null;
            /** Format: date-time */
            activeTo?: string | null;
        };
        NullValue: null;
        NullableAdminOffer: components["schemas"]["AdminOffer"] | components["schemas"]["NullValue"];
        OfferUpsertRequest: {
            offer: components["schemas"]["NullableAdminOffer"];
        };
        OfferCurrentResponse: {
            offer: components["schemas"]["NullableAdminOffer"];
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        PlanCode: "starter" | "plus" | "premium";
        PlanFeatures: {
            referral: boolean;
            offers: boolean;
        };
        PlanLimits: {
            stampsPerMonth: number | null;
            devicesAllowed: number | null;
        };
        AdminUpgradeHint: {
            usage: components["schemas"]["ReportingPlanUsage"];
            message: string;
            /** Format: uri */
            ctaUrl?: string | null;
        };
        NullableAdminUpgradeHint: components["schemas"]["AdminUpgradeHint"] | components["schemas"]["NullValue"];
        AdminPlanResponse: {
            planCode: components["schemas"]["PlanCode"];
            features: components["schemas"]["PlanFeatures"];
            limits: components["schemas"]["PlanLimits"];
            upgradeHint: components["schemas"]["NullableAdminUpgradeHint"];
        };
        StampClaimResponse: components["schemas"]["StampClaimResponsePayload"];
        StampClaimResponsePayload: {
            cardState: components["schemas"]["CardState"];
            offer?: components["schemas"]["OfferSnippet"] | null;
        };
        RedeemResponse: {
            cardState: components["schemas"]["CardState"];
        };
        DeviceRegistrationLinkResponse: {
            /** Format: uri */
            linkUrl: string;
            token: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: uri */
            qrImageUrl?: string | null;
        };
        /** @enum {string} */
        DeviceStatus: "ACTIVE" | "BLOCKED";
        Device: {
            /** Format: uuid */
            deviceId: string;
            label?: string | null;
            status: components["schemas"]["DeviceStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastSeenAt?: string | null;
        };
        DeviceListResponse: {
            devices: components["schemas"]["Device"][];
        };
        /** @enum {string} */
        AuditActorType: "ADMIN" | "SYSTEM";
        /** @enum {string} */
        AuditEventType: "device.registration_link.created" | "device.register" | "device.blocked" | "device.unblocked" | "device.removed";
        AuditEvent: {
            /** @description UUIDv7 recommended */
            eventId: string;
            eventType: components["schemas"]["AuditEventType"];
            /** Format: date-time */
            occurredAt: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            deviceId?: string | null;
            actorType: components["schemas"]["AuditActorType"];
            /** Format: uuid */
            actorId?: string | null;
            correlation_id?: string | null;
            /** @description Must not contain PII. Only pseudonymous identifiers and non-sensitive event context (e.g., deviceId, routeId, status transitions, correlation_id, rate-limit dimensions). */
            metadata?: {
                [key: string]: unknown;
            };
        };
        AuditEventListResponse: {
            events: components["schemas"]["AuditEvent"][];
            nextCursor: string | null;
        };
        ReportingCounts: {
            day: number;
            week: number;
            month: number;
        };
        ReportingRates: {
            day: number;
            week: number;
            month: number;
        };
        ReportingReferralKpis: {
            linksIssued: components["schemas"]["ReportingCounts"];
            qualified: components["schemas"]["ReportingCounts"];
            bonusStamps: components["schemas"]["ReportingCounts"];
            conversionRate: components["schemas"]["ReportingRates"];
        };
        ReportingDeviceActivity: {
            activeDevices: number;
        };
        ReportingPlanUsage: {
            period: string;
            stampsUsed: number;
            stampsLimit: number | null;
            usagePercent: number | null;
            warningEmitted: boolean;
            upgradeSignalEmitted: boolean;
        };
        ReportingSummaryResponse: {
            stamps: components["schemas"]["ReportingCounts"];
            rewards: components["schemas"]["ReportingCounts"];
            referrals: components["schemas"]["ReportingReferralKpis"];
            deviceActivity: components["schemas"]["ReportingDeviceActivity"];
            planUsage: components["schemas"]["ReportingPlanUsage"];
            activeCampaigns: number;
        };
        ReportingTimeseriesBucket: {
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
            count: number;
        };
        ReportingTimeseriesResponse: {
            /** @enum {string} */
            metric: "stamps" | "rewards" | "referral_links" | "referral_qualified" | "referral_bonus_stamps";
            /** @enum {string} */
            bucket: "day" | "week" | "month";
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            series: components["schemas"]["ReportingTimeseriesBucket"][];
        };
    };
    responses: {
        /** @description Ungültige Anfrage */
        "400BadRequest": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Nicht autorisiert */
        "401Unauthorized": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Verboten */
        "403Forbidden": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Konflikt */
        "409Conflict": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Semantisch fehlerhaft */
        "422Unprocessable": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate-Limit erreicht */
        "429RateLimited": {
            headers: {
                "Retry-After": components["headers"]["Retry-After"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Interner Serverfehler */
        "500ServerError": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Idempotenz für Schreibaktionen. 24 h gültig. */
        IdempotencyKey: string;
        /** @description Tenant context for anonymous customer flows (pseudonymous, no PII). */
        XTenantId: string;
        /** @description Pseudonymous customer card id (no PII). */
        XCardId: string;
        /** @description Pseudonymous customer card id (no PII). */
        XCardIdRequired: string;
        XDeviceProof: string;
        /** @description Unix timestamp in seconds (allowed skew ±30s). */
        XDeviceTimestamp: string;
        DsrRequestId: string;
        DeviceId: string;
    };
    requestBodies: never;
    headers: {
        /** @description Echo des Idempotenz-Schlüssels. Gültigkeit 24 h. Scope {tenantId,route,bodyHash}. */
        "Idempotency-Key": string;
        /** @description Seconds until the client may retry. */
        "Retry-After": number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRegistrationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    loginAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSessionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getReportingSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportingSummaryResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getReportingTimeseries: {
        parameters: {
            query: {
                metric: "stamps" | "rewards" | "referral_links" | "referral_qualified" | "referral_bonus_stamps";
                bucket: "day" | "week" | "month";
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportingTimeseriesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getAdminPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPlanResponse"];
                };
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            429: components["responses"]["429RateLimited"];
            500: components["responses"]["500ServerError"];
        };
    };
    getCurrentOffer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferCurrentResponse"];
                };
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            429: components["responses"]["429RateLimited"];
            500: components["responses"]["500ServerError"];
        };
    };
    upsertCurrentOffer: {
        parameters: {
            query?: never;
            header: {
                /** @description Idempotenz für Schreibaktionen. 24 h gültig. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferUpsertRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Idempotency-Key": components["headers"]["Idempotency-Key"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferCurrentResponse"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            422: components["responses"]["422Unprocessable"];
            429: components["responses"]["429RateLimited"];
            500: components["responses"]["500ServerError"];
        };
    };
    refreshAdminSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminRefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSessionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logoutAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                };
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listAdminAuditEvents: {
        parameters: {
            query?: {
                device_id?: string;
                event_type?: components["schemas"]["AuditEventType"];
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    "Retry-After": components["headers"]["Retry-After"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["500ServerError"];
        };
    };
    getJwks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JwksResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    "Retry-After": components["headers"]["Retry-After"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            500: components["responses"]["500ServerError"];
        };
    };
    blockDevice: {
        parameters: {
            query?: never;
            header: {
                /** @description Idempotenz für Schreibaktionen. 24 h gültig. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                device_id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Idempotency-Key": components["headers"]["Idempotency-Key"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["429RateLimited"];
            500: components["responses"]["500ServerError"];
        };
    };
    unblockDevice: {
        parameters: {
            query?: never;
            header: {
                /** @description Idempotenz für Schreibaktionen. 24 h gültig. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                device_id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Idempotency-Key": components["headers"]["Idempotency-Key"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["429RateLimited"];
            500: components["responses"]["500ServerError"];
        };
    };
    removeDevice: {
        parameters: {
            query?: never;
            header: {
                /** @description Idempotenz für Schreibaktionen. 24 h gültig. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                device_id: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "Idempotency-Key": components["headers"]["Idempotency-Key"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["429RateLimited"];
            500: components["responses"]["500ServerError"];
        };
    };
    createDeviceRegistrationLink: {
        parameters: {
            query?: never;
            header: {
                /** @description Idempotenz für Schreibaktionen. 24 h gültig. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Link erstellt */
            201: {
                headers: {
                    "Idempotency-Key": components["headers"]["Idempotency-Key"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRegistrationLinkResponse"];
                };
            };
            400: components["responses"]["400BadRequest"];
            401: components["responses"]["401Unauthorized"];
            403: components["responses"]["403Forbidden"];
            409: components["responses"]["409Conflict"];
            429: components["responses"]["429RateLimited"];
            500: components["responses"]["500ServerError"];
        };
    };
    confirmDeviceRegistration: {
        parameters: {
            query?: never;
            header: {
                /** @description Idempotenz für Schreibaktionen. 24 h gültig. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description Bestätigt */
            204: {
                headers: {
                    "Idempotency-Key": components["headers"]["Idempotency-Key"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["400BadRequest"];
            /** @description PLAN_NOT_ALLOWED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            409: components["responses"]["409Conflict"];
            429: components["responses"]["429RateLimited"];
            500: components["responses"]["500ServerError"];
        };
    };
    createDsrRequest: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant context for anonymous customer flows (pseudonymous, no PII). */
                "X-Tenant-Id": components["parameters"]["XTenantId"];
                /** @description Idempotenz für Schreibaktionen. 24 h gültig. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DsrRequestCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "Idempotency-Key": components["headers"]["Idempotency-Key"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DsrRequestResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description PLAN_NOT_ALLOWED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    "Retry-After": components["headers"]["Retry-After"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getDsrRequest: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant context for anonymous customer flows (pseudonymous, no PII). */
                "X-Tenant-Id": components["parameters"]["XTenantId"];
            };
            path: {
                dsr_id: components["parameters"]["DsrRequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DsrRequestStatusResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description PLAN_NOT_ALLOWED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    "Retry-After": components["headers"]["Retry-After"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    fulfillDsrRequest: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant context for anonymous customer flows (pseudonymous, no PII). */
                "X-Tenant-Id": components["parameters"]["XTenantId"];
                /** @description Idempotenz für Schreibaktionen. 24 h gültig. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                dsr_id: components["parameters"]["DsrRequestId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DsrFulfillRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Idempotency-Key": components["headers"]["Idempotency-Key"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DsrRequestStatusResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description PLAN_NOT_ALLOWED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    "Retry-After": components["headers"]["Retry-After"];
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createStampToken: {
        parameters: {
            query?: never;
            header: {
                /** @description Idempotenz für Schreibaktionen. 24 h gültig. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    "Idempotency-Key": components["headers"]["Idempotency-Key"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StampTokenResponse"];
                };
            };
            /** @description RATE_LIMITED */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    claimStamp: {
        parameters: {
            query?: never;
            header: {
                /** @description Idempotenz für Schreibaktionen. 24 h gültig. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Pseudonymous customer card id (no PII). */
                "X-Card-Id"?: components["parameters"]["XCardId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StampClaimRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StampClaimResponse"];
                };
            };
            /** @description TOKEN_EXPIRED */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description PLAN_NOT_ALLOWED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description TOKEN_REUSE | REFERRAL_TENANT_MISMATCH */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["422Unprocessable"];
            /** @description RATE_LIMITED */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    redeemReward: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Proof": components["parameters"]["XDeviceProof"];
                /** @description Unix timestamp in seconds (allowed skew ±30s). */
                "X-Device-Timestamp": components["parameters"]["XDeviceTimestamp"];
                /** @description Idempotenz für Schreibaktionen. 24 h gültig. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    redeemToken: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedeemResponse"];
                };
            };
            /** @description TOKEN_EXPIRED */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description PLAN_NOT_ALLOWED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description TOKEN_REUSE */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            429: components["responses"]["429RateLimited"];
            500: components["responses"]["500ServerError"];
        };
    };
    getReferralLink: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant context for anonymous customer flows (pseudonymous, no PII). */
                "X-Tenant-Id": components["parameters"]["XTenantId"];
                /** @description Pseudonymous customer card id (no PII). */
                "X-Card-Id": components["parameters"]["XCardIdRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        refCodeURL: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
